#!/bin/bash
#### Non-Customizable Header ####
# BASH_BOILER_VERSION=2019.07.11.01
# Generated with Bash-Boiler on 07-26-19_17:44:09
# Use updater to update this script:
# https://github.com/coreyramirezgomez/Bash-Boiler.git
# Modifying any content between blocks like the following:
# "#### Non-Customizable ... #####"
# ....
# "#### ####"
# will be overwritten by Bash-Boiler updater function.
trap catch_exit $?
#### ####

#### Custom Header ####
#### ####

#### Non-Customizable Global Variables ####
QUIET=""
START_TIME="$(date +%s)"
START_DATE="$(date +%m-%d-%y_%H:%M:%S)"
VERBOSE=""
#### ####

#### Customizable Variables ####
ARGS_REQUIRED=1
BINARIES_REQUIRED=( "autopkg" "/usr/libexec/PlistBuddy" )
GARBAGE_COLLECTOR=0
GARBAGE=()
DEBUG=0
FORCE_FLAG=0
WORK_DIR="$(pwd)" # Only variable not in alphabetical order because LOG_FILE depends on it.
LOG_FILE="$WORK_DIR/""$(basename $0).log"
LOGGING=0
#### ####

#### Custom Variables ####
ACTIONS=()
OVERRIDE_DIR="$(defaults read com.github.autopkg RECIPE_OVERRIDE_DIRS)"
SELECT=0
RECIPE_NAMES=()
ADD_CATALOGS=()
REMOVE_CATALOGS=()
#### ####

#### Non-Customizable Functions ####
backup_file()
{
	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args ($#): $*"
	[ $# -lt 1 ] && fail_notice_exit "(${FUNCNAME[0]}) Not enough arguments received." 101
	case $# in
		1)
			backup_target="$1"
			debug_print -e -Y -S "(${FUNCNAME[0]}) No backup destination specified."
			backup_dest="$1-backup-$(date +%m-%d-%y_%H:%M:%S)"
			debug_print -e -Y -S "(${FUNCNAME[0]}) Using default: $backup_dest"
			;;
		2)
			backup_target="$1"
			backup_dest="$2"
			;;
		*)
			debug_print -e -Y -S "(${FUNCNAME[0]}) More that 2 arguments provided: $*"
			debug_print -e -Y -S "(${FUNCNAME[0]}) Only using first 2."
			backup_target="$1"
			backup_dest="$2"
			;;
	esac

	if [ ! -f "$backup_target" ]; then
		local_print -R -S "(${FUNCNAME[0]}) No file to backup @ $backup_target"
		return 1
	fi
	if	[ -d "$backup_dest" ]; then
		local_print -R -S "(${FUNCNAME[0]}) Backup destination is a directory: $backup_dest"
		return 1
	fi
	if [ -f "$backup_dest" ]; then
		local_print -Y -S "(${FUNCNAME[0]}) File already exists @ $backup_dest"
		get_response "(${FUNCNAME[0]}) Would you like to backup $backup_dest?"
		[ $? -eq 1 ] && return 1
		backup_file "$backup_dest"
		[ $? -ne 0 ] && return 1
	fi
	cp -f"$VERBOSE" -- "$backup_target" "$backup_dest"
	[ $? -ne 0 ] && fail_notice_exit "(${FUNCNAME[0]}) Backup failure for $backup_target" $?
	debug_print -e -B -S "Successfully created backup of $backup_target to $backup_dest"
	return 0
}
catch_exit()
{
	code=$?
	debug_print -e -B -S "(${FUNCNAME[0]}) START DATE: $START_DATE"
	debug_print -e -B -S "(${FUNCNAME[0]}) END DATE: $(date +%m-%d-%y_%H:%M:%S)"
	debug_print -e -B -S "$0 ran for  $(( $(date +%s) - $START_TIME ))s"
	case $code in
			# Exit codes from https://www.tldp.org/LDP/abs/html/exitcodes.html
		0) debug_print -e -G -S "(${FUNCNAME[0]}) Successful Exit: $code" ;;
		1) debug_print -e -R -S "(${FUNCNAME[0]}) General Fatal Exit: $code " ;;
		2) debug_print -e -R -S "(${FUNCNAME[0]}) Misuse of shell builtins: $code" ;;
		126) debug_print -e -R -S "(${FUNCNAME[0]}) Command invoked cannot execute: $code" ;;
		127) debug_print -e -R -S "(${FUNCNAME[0]}) Command not found: $code" ;;
		128) debug_print -e -R -S "(${FUNCNAME[0]}) Invalid argument to exit: $code" ;;
		129|13[0-9]|14[0-9]|15[0-9]|16[0-5])debug_print -e -R -S "(${FUNCNAME[0]}) Fatal error signal: $code" ;;
		130) debug_print -e -Y -S "(${FUNCNAME[0]}) Script terminated by Control-C: $code" ;;
			# Custom exit codes
		100) debug_print -e -Y -S "(${FUNCNAME[0]}) Unspecified error: $code" ;;
		101) debug_print -e -R -S "(${FUNCNAME[0]}) Missing required variable or argument: $code" ;;
	esac
	catch_exit_custom "$code"
	if [ $GARBAGE_COLLECTOR -eq 1 ]; then
		for t in "${GARBAGE[@]}"
		do
			garbage_dump "$t"
		done
	fi
	debug_print -e -B -S "======= End of Run for $0 ======="
}
check_binaries()
{
	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args ($#): $*"
	if [ $# -lt 1 ];then
		debug_print -e -Y -S "(${FUNCNAME[0]}) Not enough arguments received."
		return 0
	fi
	debug_print -e -B -S "(${FUNCNAME[0]}) Using PATH=$PATH"
	missing=0
	arr=("$@")
	debug_print -e -B -S "(${FUNCNAME[0]}) Received binary package list: ${arr[*]}"
	for p in "${arr[@]}"
	do
		if which "$p"  >&/dev/null; then
			debug_print -e -G -S "(${FUNCNAME[0]}) Found $p"
		else
			debug_print -e -Y -S "(${FUNCNAME[0]}) Missing binary package: $p"
			((missing++))
		fi
	done
	return $missing
}
garbage_add()
{
	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args ($#): $*"
	[ $# -lt 1 ] && fail_notice_exit "(${FUNCNAME[0]}) Not enough arguments received." 101
	for a in "$@"
	do
		debug_print -e -B -S "(${FUNCNAME[0]}) Adding to GARBAGE pile: $a"
		GARBAGE=( "${GARBAGE[@]}" "$a" )
	done
	return 0
}
garbage_dump()
{
	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args ($#): $*"
	[ $# -lt 1 ] && fail_notice_exit "(${FUNCNAME[0]}) Not enough arguments received." 101
	for i in "$@"
	do
		if [ -f "$i" ];then
			debug_print -e -Y -S "(${FUNCNAME[0]}) Removing file: $i"
			rm -f"$VERBOSE" "$i"
			return_code=$?
		elif [ -d "$i" ];then
			debug_print -e -Y -S "(${FUNCNAME[0]}) Removing directory: $i"
			rm -rf"$VERBOSE" "$i"
			return_code=$?
		else
			debug_print -e -R -S "(${FUNCNAME[0]}) $i doesn't exist."
			return_code=0
		fi
	done
	return $return_code
}
debug_state()
{
	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args ($#): $*"
	debug_print -e -B -S "(${FUNCNAME[0]}) Current Template Variable State: "
	debug_print -e -B -S "(${FUNCNAME[0]}) WORK_DIR: $WORK_DIR"
	debug_print -e -B -S "(${FUNCNAME[0]}) FORCE_FLAG: $(var_state $FORCE_FLAG)"
	debug_print -e -B -S "(${FUNCNAME[0]}) DEBUG: $(var_state $DEBUG)"
	debug_print -e -B -S "(${FUNCNAME[0]}) VERBOSE: $VERBOSE"
	debug_print -e -B -S "(${FUNCNAME[0]}) QUIET: $QUIET"
	debug_print -e -B -S "(${FUNCNAME[0]}) START_DATE: $START_DATE"
	debug_print -e -B -S "(${FUNCNAME[0]}) START_TIME: $START_TIME"
	debug_print -e -B -S "(${FUNCNAME[0]}) LOG_FILE: $LOG_FILE"
	debug_print -e -B -S "(${FUNCNAME[0]}) LOGGING: $(var_state $LOGGING)"
	debug_print -e -B -S "(${FUNCNAME[0]}) BINARIES_REQUIRED: ${BINARIES_REQUIRED[*]}"
	debug_print -e -B -S "(${FUNCNAME[0]}) BINARIES_OPTIONAL: ${BINARIES_OPTIONAL[*]}"
	debug_state_custom
}
fail_notice_exit()
{
	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args ($#): $*"
	case "$#" in
		0)
			desc="Unknown"
			error_code=100
			;;
		1)
			desc="$1"
			error_code=100
			;;
		2)
			desc="$1"
			error_code="$2"
			;;
		*)
			debug_print -e -Y "(${FUNCNAME[0]}) Received more than 2 required args: $*"
			desc="$1"
			error_code="$2"
			;;
	esac
	local_print -e -R -S "Failure: $desc"
	exit $error_code
}
get_response()
{
	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args ($#): $*"
	[ $# -lt 1 ] && fail_notice_exit "(${FUNCNAME[0]}) Not enough arguments received." 101
	debug_print -e -B -S "(${FUNCNAME[0]}) Received question: $1"
	reply=""
	[ $FORCE_FLAG -eq 1 ] && reply="y"
	while :
	do
		case "$reply" in
			"N" | "n")
				debug_print -e -B -S "(${FUNCNAME[0]}) Returning $reply (1) reply."
				return 1
				;;
			"Y" | "y")
				debug_print -e -B -S "(${FUNCNAME[0]}) Returning $reply (0) reply."
				return 0
				;;
			*)
				local_print -e -Y -n "$1 (Y/N): "
				read -n 1 reply
				echo ""
				debug_print -e -B -S "(${FUNCNAME[0]}) Question answered with: $reply"
				;;
		esac
	done
}
local_print()
{
	if [ $LOGGING -eq 1 ]; then
		cprint -l "$LOG_FILE" "$@"
	else
		cprint "$@"
	fi
}
debug_print()
{
	if [ $LOGGING -eq 1 ] && [ $DEBUG -eq 1 ]; then
		cprint -l "$LOG_FILE" "$@"
	elif [ $LOGGING -eq 1 ] && [ $DEBUG -eq 0 ]; then
		cprint -l "$LOG_FILE" "$@" >/dev/null 2>&1
	elif [ $LOGGING -eq 0 ] && [ $DEBUG -eq 1 ]; then
		cprint "$@"
	fi
}
main()
{
	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args ($#): $*"
	[ $DEBUG -eq 1 ] && VERBOSE="v"
	[ $DEBUG -eq 0 ] && QUIET="q"
	if [ $LOGGING -eq 1 ] && [ ! -f "$LOG_FILE" ]; then
		touch "$LOG_FILE" || fail_notice_exit "(${FUNCNAME[0]}) Unable to create log file @ $LOG_FILE"
		debug_print -e -B -S "(${FUNCNAME[0]}) Created Log File: $LOG_FILE @ $START_DATE"
	fi
	debug_state
	check_binaries "${BINARIES_REQUIRED[@]}"
	[ $? -ne 0 ] && fail_notice_exit "(${FUNCNAME[0]}) Missing $? required binaries."
	main_custom
}
parse_args()
{
	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args ($#): $*"
	EXTRA_ARGS=()
	while [ ${#} -gt 0 ]; do
		case "${1}" in
			"--help" | "-h") usage ;;
			"--debug") DEBUG=$(var_toggle $DEBUG) ;;
			"--force" | "-f") FORCE_FLAG=$(var_toggle $FORCE_FLAG) ;;
			"--garbage-collect") GARBAGE_COLLECTOR=$(var_toggle $GARBAGE_COLLECTOR) ;;
			"--logging"| "-l") LOGGING=$(var_toggle $LOGGING) ;;
			"--logfile")
				[ -d "$2" ] && fail_notice_exit "(${FUNCNAME[0]}) Invalid logfile, it is a directory: $2"
				LOG_FILE="$2"
				shift
				;;
			"--work_dir")
				[ ! -d "$2" ] && fail_notice_exit "(${FUNCNAME[0]}) Invalid directory: $2"
				WORK_DIR="$2"
				shift
				;;
			*)
				debug_print -B "(${FUNCNAME[0]}) Extra Arg Received ($1), saving for custom parser."
				EXTRA_ARGS=( "${EXTRA_ARGS[@]}" "$1" )
				;;
		esac
		shift 1
	done
	parse_args_custom "${EXTRA_ARGS[@]}"
}
usage()
{
	echo ""
	echo "Usage for $0:"
	echo ""
	echo -n "	--garbage-collect: Toggle garbage-collect flag. Removes all files/directory variables in GARBAGE array. Default: "
	[ $GARBAGE_COLLECTOR -eq 0 ] && local_print -R "$(var_state $GARBAGE_COLLECTOR)"
	[ $GARBAGE_COLLECTOR -eq 1 ] && local_print -G "$(var_state $GARBAGE_COLLECTOR)"
	echo -n "	--debug: Toggle Debugging. Default: "
	[ $DEBUG -eq 0 ] && local_print -R "$(var_state $DEBUG)"
	[ $DEBUG -eq 1 ] && local_print -G "$(var_state $DEBUG)"
	echo -n "	--force: Answer 'yes'/'y' to all questions. (aka force) Default: "
	[ $FORCE_FLAG -eq 0 ] && local_print -R "$(var_state $FORCE_FLAG)"
	[ $FORCE_FLAG -eq 1 ] && local_print -G "$(var_state $FORCE_FLAG)"
	echo "	[--help|-h]: Display this dialog"
	echo -n "	[--logging|-l]: Toggle logging. Default: "
	[ $LOGGING -eq 0 ] && local_print -R "$(var_state $LOGGING)"
	[ $LOGGING -eq 1 ] && local_print -G "$(var_state $LOGGING)"
	echo "	--logfile filename: Specifiy the logfile output. Default: $LOG_FILE"
	usage_custom
	echo ""
	exit 0
}
var_state()
{
	case $1 in
		0) echo "OFF" ;;
		1) echo "ON" ;;
		*) echo "Unknown ($1)"
	esac
}
var_toggle()
{
	case $1 in
		[0-1]) echo $(( (($1 + 1 )) % 2 )) ;;
		*) fail_notice_exit "(${FUNCNAME[0]}) Can't toggle: $1"
	esac
}
#### ####

#### Non-Customizable External Template Functions ####

cprint()
{
	CPRINT_process_nl()
	{
		if [ -z ${CPRINT_NL} ]; then
			[ ! -z ${CPRINT_ERR_OUT} ] && (>&2 echo "") || echo ""
		fi
	}
	CPRINT_process_prenl()
	{
		if [ ! -z ${PCPRINT_NL} ]; then
			while [ $PCPRINT_NL -gt 0 ]
			do
				[ ! -z ${CPRINT_ERR_OUT} ] && (>&2 echo "") || echo ""
				[ ! -z ${CPRINT_LOG_CPRINT_STYLED} ] && echo ""  >> "$CPRINT_LOG_CPRINT_STYLED"
				[ ! -z ${CPRINT_LOG} ] && echo ""  >> "$CPRINT_LOG"
				((PCPRINT_NL--))
			done
		fi
	}
	CPRINT_process_string()
	{
		[ -z "${CPRINT_STRING}" ] && CPRINT_STRING=""
		[ ! -z ${CPRINT_LOG} ] && echo "$CPRINT_STRING" >> "$CPRINT_LOG"
		[ -z ${CPRINT_POS} ] && CPRINT_POS=0 # Position is not set, so use the default.
		[ ! -z ${CPRINT_STYLE} ] && CPRINT_STRING="$($CPRINT_STYLE $CPRINT_STRING)" # Apply style
		[ -z "${CPRINT_FOREGROUND}" ] && CPRINT_FOREGROUND=""
		[ -z "${CPRINT_BACKGROUND}" ] && CPRINT_BACKGROUND=""
		RESET=$(CPRINT_translate_color_code "RESET")
		if [ ! -f "$(which printf 2>/dev/null)" ] || [ ! -z ${USE_ECHO} ]; then
			[ ! -z ${CPRINT_ERR_OUT} ] && (>&2 echo -n -e "$CPRINT_FOREGROUND""$CPRINT_BACKGROUND""$CPRINT_STRING""$RESET") || echo -n -e "$CPRINT_FOREGROUND""$CPRINT_BACKGROUND""$CPRINT_STRING""$RESET"
		else
			[ ! -z ${CPRINT_ERR_OUT} ] && (>&2 printf -- "$CPRINT_FOREGROUND$CPRINT_BACKGROUND%$CPRINT_POS"s"$RESET" "$CPRINT_STRING") || printf -- "$CPRINT_FOREGROUND$CPRINT_BACKGROUND%$CPRINT_POS"s"$RESET" "$CPRINT_STRING"
		fi
		[ ! -z ${CPRINT_LOG_CPRINT_STYLED} ] && echo -e "$CPRINT_STRING" >> "$CPRINT_LOG_CPRINT_STYLED"
	}
	CPRINT_random_color()
	{
		local colors=( "BLACK" "WHITE" "RED" "YELLOW" "GREEN" "BLUE" "CYAN" "PURPLE" )
		echo "${colors[$RANDOM % ${#colors[@]}]}"
	}
	CPRINT_translate_color_code()
	{
		if [ $# -lt 1 ]; then
			echo "Missing color name."
			exit 1
		fi
		local CODE=""
		case "$1" in
			"FG"*)
				case "$1" in
					*"BLACK" ) CODE='30m' ;;
					*"WHITE" ) CODE='37m' ;;
					*"RED" ) CODE='31m' ;;
					*"YELLOW" ) CODE='33m' ;;
					*"GREEN" ) CODE='32m' ;;
					*"BLUE" ) CODE='34m' ;;
					*"CYAN" ) CODE='36m' ;;
					*"PURPLE" ) CODE='35m' ;;
				esac
				if [ ! -z ${CPRINT_BOLD} ]; then
					if [ $CPRINT_BOLD -eq 1 ]; then
						CODE='1;'$CODE
					fi
				else
					CODE='0;'$CODE
				fi
				;;
			"BG"*)
				case "$1" in
					*"BLACK" ) CODE='40m' ;;
					*"WHITE" ) CODE='47m' ;;
					*"RED" ) CODE='41m' ;;
					*"YELLOW" ) CODE='43m' ;;
					*"GREEN" ) CODE='42m' ;;
					*"BLUE" ) CODE='44m' ;;
					*"CYAN" ) CODE='46m' ;;
					*"PURPLE" ) CODE='45m' ;;
				esac
				;;
			"RESET") CODE='m' ;;
		esac
		case "$(uname -s)" in
			"Darwin" | "FreeBSD") echo "\033[""$CODE" ;;
			"Linux") echo "\e[""$CODE" ;;
			*)
				echo "Unknown System: $(uname -s)"
				exit 1
				;;
		esac
	}
	CPRINT_parse_args()
	{
		while [ ${#} -gt 0 ];
		do
			case "${1}" in
				"-e" | "--stderr") CPRINT_ERR_OUT=1 ;;
				"-n" | "no-newline") CPRINT_NL=1 ;;
				"-p" | "--pre-newline")
					[ -z ${PCPRINT_NL} ] && PCPRINT_NL=0
					((PCPRINT_NL++))
					;;
				"-I" | "-b" | "--bold" ) CPRINT_BOLD=1 ;;
				"-A" | "--cowsay")
					if [ -f "$(which cowsay 2>/dev/null)" ]; then
						CPRINT_STYLE="$(which cowsay)"
					else
						(>&2 echo "Skipping $1 becasue, binary not available.")
					fi
					;;
				"-F" | "--figlet")
					if [ -f "$(which figlet 2>/dev/null)" ]; then
						CPRINT_STYLE="$(which figlet)"
					else
						(>&2 echo "Skipping $1 becasue, binary not available.")
					fi
					;;
				"--cow-file" | "--fig-file")
					if [ ! -z "${CPRINT_STYLE}" ]; then
						if [ ! -f "$2" ]; then
							(>&2 echo "Skipping $1 because, not a valid file: $2.")
						else
							CPRINT_STYLE="$CPRINT_STYLE -f $2"
						fi
					else
						(>&2 echo "Skipping $1 because, CPRINT_STYLE not set.")
					fi
					;;
				"-c" | "--centered") [ $(tput cols) -le 80 ] && CPRINT_POS=0 || CPRINT_POS=$((( $(tput cols) - 80 ) / 2 )) ;;
				"--BG" | "--bg" | "--background" | "--FG" | "--fg"| "--foreground")
					local TYPE=""
					local COLOR_CODE=""
					case "$1" in
						"--BG" | "--bg" | "--background") TYPE="BG" ;;
						"--FG" | "--fg" | "--foreground") TYPE="FG" ;;
					esac
					case "$2" in
						"black") COLOR_CODE="$(CPRINT_translate_color_code "$TYPE"'BLACK')" ;;
						"white") COLOR_CODE="$(CPRINT_translate_color_code "$TYPE"'WHITE')" ;;
						"red") COLOR_CODE="$(CPRINT_translate_color_code "$TYPE"'RED')" ;;
						"yellow") COLOR_CODE="$(CPRINT_translate_color_code "$TYPE"'YELLOW')" ;;
						"green") COLOR_CODE="$(CPRINT_translate_color_code "$TYPE"'GREEN')" ;;
						"blue") COLOR_CODE="$(CPRINT_translate_color_code "$TYPE"'BLUE')" ;;
						"cyan") COLOR_CODE="$(CPRINT_translate_color_code "$TYPE"'CYAN')" ;;
						"purple") COLOR_CODE="$(CPRINT_translate_color_code "$TYPE"'PURPLE')" ;;
						"random") COLOR_CODE="$(CPRINT_translate_color_code "$TYPE""$(CPRINT_random_color)")" ;;
						"*")
							(>&2 echo "Unrecognized Arguement: $2")
							exit 1
							;;
					esac
					case "$1" in
						"--BG" | "--bg" | "--background") CPRINT_BACKGROUND="$COLOR_CODE" ;;
						"--FG" | "--fg" | "--foreground") CPRINT_FOREGROUND="$COLOR_CODE" ;;
					esac
					shift
					;;
				"-K" | "--black") CPRINT_FOREGROUND="$(CPRINT_translate_color_code 'FGBLACK')" ;;
				"-W" | "--white") CPRINT_FOREGROUND="$(CPRINT_translate_color_code 'FGWHITE')" ;;
				"-R" | "--red") CPRINT_FOREGROUND="$(CPRINT_translate_color_code 'FGRED')" ;;
				"-Y" | "--yellow") CPRINT_FOREGROUND="$(CPRINT_translate_color_code 'FGYELLOW')" ;;
				"-G" | "--green") CPRINT_FOREGROUND="$(CPRINT_translate_color_code 'FGGREEN')" ;;
				"-B" | "--blue") CPRINT_FOREGROUND="$(CPRINT_translate_color_code 'FGBLUE')" ;;
				"-C" | "--cyan") CPRINT_FOREGROUND="$(CPRINT_translate_color_code 'FGCYAN')" ;;
				"-P" | "--purple") CPRINT_FOREGROUND="$(CPRINT_translate_color_code 'FGPURPLE')" ;;
				"--use-echo") USE_ECHO=1 ;;
				"-Z" | "--random") CPRINT_FOREGROUND="$(CPRINT_translate_color_code "FG$(CPRINT_random_color)")" ;;
				"-L" | "--log-styled")
					if [ -d "$2" ]; then
						echo "Specified filename is a directory: $2"
						exit 1
					fi
					CPRINT_LOG_CPRINT_STYLED="$2"
					shift
					;;
				"-l" | "--log")
					if [ -d "$2" ]; then
						echo "Specified filename is a directory: $2"
						exit 1
					fi
					CPRINT_LOG="$2"
					shift
					;;
				"-S" | "--string")
					shift
					CPRINT_STRING="$*"
					break
					;;
				*)
					CPRINT_STRING="$*"
					break
					;;
			esac
			shift 1
		done
	}
	CPRINT_parse_args "$@"
	if [ -z "${CPRINT_STRING}" ]; then
		CPRINT_STRING="$*"
	fi
	if [ ! -z "${CPRINT_STRING}" ]; then
		CPRINT_process_prenl
		CPRINT_process_string
		CPRINT_process_nl
	fi
	unset CPRINT_ERR_OUT
	unset CPRINT_NL
	unset CPRINT_PNL
	unset CPRINT_BOLD
	unset CPRINT_STYLE
	unset CPRINT_POS
	unset CPRINT_BACKGROUND
	unset CPRINT_FOREGROUND
	unset CPRINT_LOG
	unset CPRINT_LOG_STYLED
	unset CPRINT_STRING
}
#### ####

#### Customizable Functions ####
catch_exit_custom()
{
	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args: $*"
}
debug_state_custom()
{
	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args: $*"
	debug_print -e -B -S "(${FUNCNAME[0]}) Current Custom Variable State: "
}
get_autopkg_trust_behavior()
{
	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args: $*"
	R=$(defaults read com.github.autopkg FAIL_RECIPES_WITHOUT_TRUST_INFO 2>/dev/null)
	if [ $? -ne 0 ]; then
		debug_print -B -S "(${FUNCNAME[0]}) Key FAIL_RECIPES_WITHOUT_TRUST_INFO not set or some other error ($?)."
		return 66
	else
		case "$R" in
			0)
				debug_print -R -S "(${FUNCNAME[0]}) FAIL_RECIPES_WITHOUT_TRUST_INFO set to False."
				return 0
				;;
			1)
				debug_print -G -S "(${FUNCNAME[0]}) FAIL_RECIPES_WITHOUT_TRUST_INFO set to True."
				return 1
				;;
			*)
				debug_print -R -S "(${FUNCNAME[0]}) FAIL_RECIPES_WITHOUT_TRUST_INFO set to Unknown value: $R."
				return 66
				;;
		esac
	fi
}
set_autopkg_trust_behavior()
{
	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args: $*"
	[ $# -lt 1 ] && fail_notice_exit "(${FUNCNAME[0]}) Not enough arguments provided."
	case "$1" in
		0 | "true" | "yes" | "YES" | "TRUE")
			action="write"
			value="-bool YES"
			;;
		1 | "false" | "no" | "NO" | "FALSE")
			action="write"
			value="-bool NO"
			;;
		"NONE" | "none" | "RESET" | "reset")
			value=""
			action="delete"
			;;
		*)
			fail_notice_exit "(${FUNCNAME[0]}) Incorrect argument provided."
			;;
	esac
	defaults $action com.github.autopkg FAIL_RECIPES_WITHOUT_TRUST_INFO $value
	return_code=$?
	case "$return_code" in
		0) debug_print -G -S "(${FUNCNAME[0]}) Successful action $action to FAIL_RECIPES_WITHOUT_TRUST_INFO with value: $value" ;;
		*) debug_print -R -S "(${FUNCNAME[0]}) Failed action $action to FAIL_RECIPES_WITHOUT_TRUST_INFO with value: $value" ;;
	esac
	return $return_codes
}
main_custom()
{
	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args: $*"
	BLOCK="##########"
	for R in "${RECIPE_NAMES[@]}"
	do
		ADD_CATALOG_COUNT=0
		REMOVE_CATALOG_COUNT=0
		for A in "${ACTIONS[@]}"
		do
			local_print -C -S "$BLOCK Performing $A Action for $R $BLOCK"
			case $A in
				"ADD_CATALOG")
					local_print -C -S "Adding Catalog ${ADD_CATALOG[$ADD_CATALOG_COUNT]}"
					add_catalog "$R" "${ADD_CATALOG[$ADD_CATALOG_COUNT]}"
					return_code=$?
					((ADD_CATALOG_COUNT++))
					;;
				"FORMAT_SUBDIR")
					update_subdir "$R"
					return_code=$?
					;;
				"INFO")
					autopkg info --override-dir="$OVERRIDE_DIR" "$R"
					return_code=$?
					;;
				"REMOVE_CATALOG")
					local_print -C -S "Removing Catalog ${REMOVE_CATALOG[$REMOVE_CATALOG_COUNT]}"
					remove_catalog "$R" "${REMOVE_CATALOG[$REMOVE_CATALOG_COUNT]}"
					return_code=$?
					((ADD_CATALOG_COUNT++))
					;;
				"TRUST")
					autopkg update-trust-info --override-dir="$OVERRIDE_DIR" "$R"
					return_code=$?
					[ $return_code -eq 0 ] && local_print -G -S "Trust Successful for $R"
					[ $return_code -ne 0 ] && local_print -R -S "Trust Failed for $R"
					;;
				"VERIFY")
					autopkg verify-trust-info --override-dir="$OVERRIDE_DIR" "$R"
					return_code=$?
					;;
				*) fail_notice_exit "(${FUNCNAME[0]}) Unknown action: $A";;
			esac
			[ $return_code -eq 0 ] && local_print -G -S "$BLOCK Done ($return_code) $BLOCK"
			[ $return_code -ne 0 ] && local_print -Y -S "$BLOCK Done ($return_code) $BLOCK"
		done
	done
}
parse_args_custom()
{
	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args: $*"
	while [ ${#} -gt 0 ]; do
		case "${1}" in
			"--info" | "--i") ACTIONS=( "${ACTIONS[@]}" "INFO" );;
			"--name" | "--n")
				RECIPE_NAMES=( "${RECIPE_NAMES[@]}" "$2" )
				shift
				;;
			"--add-catalog")
				ACTIONS=( "${ACTIONS[@]}" "ADD_CATALOG" )
				ADD_CATALOGS=( "${ADD_CATALOGS[@]}" "$2" )
				shift
				;;
			"--remove-catalog")
				ACTIONS=( "${ACTIONS[@]}" "REMOVE_CATALOG" )
				REMOVE_CATALOGS=( "${REMOVE_CATALOGS[@]}" "$2" )
				shift
				;;
			"--remove-catalog-all")
				ACTIONS=( "${ACTIONS[@]}" "REMOVE_CATALOG" )
				REMOVE_CATALOGS=( "ALL" )
				;;
			"--override-dir")
				[ ! -d "$2" ] && fail_notice_exit "(${FUNCNAME[0]}) Invalid override_dir, it is not a directory: $2"
				OVERRIDE_DIR="$2"
				shift
				;;
			"--format-repo-subdir") ACTIONS=( "${ACTIONS[@]}" "FORMAT_SUBDIR" );;
			"--select" | "--s") SELECT=$(var_toggle $SELECT);;
			"--set-trust-behavior-"*)
				set_autopkg_trust_behavior "$(echo $1 | cut -d '-' -f6)"
				[ $? -ne 0 ] && fail_notice_exit "Failed to set FAIL_RECIPES_WITHOUT_TRUST_INFO to $(echo $1 | cut -d '-' -f6)"
				exit 0
				;;
			"--trust" | "-t") ACTIONS=( "${ACTIONS[@]}" "TRUST" );;
			"--verify" | "-v") ACTIONS=( "${ACTIONS[@]}" "VERIFY" );;
			*)
				debug_print -e -B -S "Processing Unknown Argument: $1"
				if [ ${#} -eq 1 ];then
					RECIPE_NAMES=( "${RECIPE_NAMES[@]}" "$1")
				else
					fail_notice_exit "(${FUNCNAME[0]}) Unknown argument: $1" 1
				fi
				;;
		esac
		shift 1
	done
	[ ! -d "$OVERRIDE_DIR" ] && fail_notice_exit "(${FUNCNAME[0]}) OVERRIDE_DIR ($OVERRIDE_DIR) does not exist."
	# Get available override names, since we might need them later.
	cd "$OVERRIDE_DIR" || fail_notice_exit "(${FUNCNAME[0]}) Failed to cd into $OVERRIDE_DIR."
	available_overrides=()
	for f in *.recipe
	do
		available_overrides=( "${available_overrides[@]}" "$f" )
	done
	IFS=$'\n'
	available_overrides=( $(sort -f <<< "${available_overrides[*]}" ) )
	unset IFS
	cd "$WORK_DIR" || fail_notice_exit "(${FUNCNAME[0]}) Failed to cd into $WORK_DIR"

	if [ $SELECT -eq 1 ]; then
		while :
		do
			INDEX=0
			for o in "${available_overrides[@]}" "ALL"
			do
				enabled=0
				for n in "${RECIPE_NAMES[@]}"
				do
					[[ "$o" == "$n" ]] && enabled=1 && break
				done
				if [ $enabled -eq 1 ]; then
					cprint -G -S "[$INDEX] $o"
				else
					cprint -R -S "[$INDEX] $o"
				fi
				((INDEX++))
			done
			index_selection=-1
			echo -n "Select an option (enter to finish): "
			read index_selection
			if [[ $index_selection =~ ^[0-9]+$ ]] && [ $index_selection -gt -1 ]; then
				if [ $index_selection -lt ${#available_overrides[@]} ]; then
					RECIPE_NAMES=( "${RECIPE_NAMES[@]}" "${available_overrides[$index_selection]}" )
				elif [ $index_selection -eq ${#available_overrides[@]} ]; then
					RECIPE_NAMES=( "${available_overrides[@]}" )
					break
				else
					local_print -e -Y -S "Invalid selection: $index_selection"
					index_selection=-1
				fi
			elif [[ "$index_selection" == "" ]]; then
				break
			else
				local_print -e -Y -S "Invalid selection: $index_selection"
				index_selection=-1
			fi
		done
	fi
	[ ${#RECIPE_NAMES[@]} -eq  0 ] && fail_notice_exit "(${FUNCNAME[0]}) No recipe names specifed."
	for R in "${RECIPE_NAMES[@]}"
	do
		if [[ "$R" == "ALL" ]]; then
			RECIPE_NAMES=( "${available_overrides[@]}" )
			break
		fi
	done
}
usage_custom()
{
	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args: $*"
	echo ""
	echo "	[OPTIONS] [RECIPE_NAME]"
	echo "	[--info|-i]: Show recipe info."
	echo "	[--name|-n] recipe: Specifiy a recipe name. Use this flage for each recipe. Specifying 'ALL' will select all recipes available in the OVERRIDE_DIR."
	echo "	--override-dir absolute-path-to-dir: Set the Override Directory. Default: $OVERRIDE_DIR"
	echo -n "	[--select|-s]: Interactively select a recipe from specified Override Directory. Default: "
	[ $SELECT -eq 0 ] && local_print -R "$(var_state $SELECT)"
	[ $SELECT -eq 1 ] && local_print -G "$(var_state $SELECT)"
	echo "	--add-catalog catalog: Add a catalog to a recipe."
	echo "	--remove-catalog catalog: Remove a catalog from a recipe."
	echo "	--remove-catalog-all: Remove all catalogs from a recipe."
	echo "	--format-repo-subdir: Format the MUNKI_REPO_SUBDIR to be developer_name/app_name."
	echo "	[--trust|-t]: Trust a recipe."
	echo "	[--verify|-v]: Verify trust info."
	echo ""
	echo "	[OPTIONS]"
	echo "	--get-trust-behavior: Retrieve the value of FAIL_RECIPES_WITHOUT_TRUST_INFO from com.github.autopkg."
	echo "	--set-trust-behavior-[true|false|none]: Set the value of FAIL_RECIPES_WITHOUT_TRUST_INFO for com.github.autopkg to true, false or none."
}
#### ####

#### Custom Functions ####
update_subdir()
{
	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args: $*"
	[ $# -lt 1 ] && fail_notice_exit "(${FUNCNAME[0]}) Missing required argument."
	RECIPE_FILE=$OVERRIDE_DIR/$1
	app_name=$(/usr/libexec/PlistBuddy "$RECIPE_FILE" -c "print Input:NAME")
	if [ $? -ne 0 ]; then
		local_print -R -S "(${FUNCNAME[0]}) Failed to retrieve applcation name for $1."
		return 1
	fi
	app_dev=$(/usr/libexec/PlistBuddy "$RECIPE_FILE" -c "print Input:pkginfo:developer" 2> /dev/null )
	if [ $? -ne 0 ]; then
		local_print -Y -S "(${FUNCNAME[0]}) No developer key for $1. Adding empty key to fill later."
		/usr/libexec/PlistBuddy "$RECIPE_FILE" -c "add Input:pkginfo:developer string"
		[ $? -ne 0 ] && local_print -R -S "(${FUNCNAME[0]}) Failed to add developer key to $1."
	fi
	if [[ $app_dev == "" ]]; then
		local_print -n -G -S "Enter developer name: "
		read app_dev </dev/tty
		debug_print --use-echo -G -S "(${FUNCNAME[0]}) Set developer name to: $app_dev"
	fi
	current_subdir_name=$(/usr/libexec/PlistBuddy "$RECIPE_FILE" -c "print Input:MUNKI_REPO_SUBDIR" 2> /dev/null)
	if [ $? -ne 0 ]; then
		local_print -R  -S "(${FUNCNAME[0]}) Failed to retrieve MUNKI_REPO_SUBDIR for $1."
		return 1
	fi
	debug_print --use-echo -B -S "(${FUNCNAME[0]}) Retrieved Application Name: $app_name"
	debug_print --use-echo -B -S "(${FUNCNAME[0]}) Retrieved Developer Name: $app_dev"

	debug_print --use-echo -B -S "(${FUNCNAME[0]}) Current MUNKI_REPO_SUBDIR: $current_subdir_name"
	if [[ $app_dev != "" ]]; then
		local_print --use-echo -Y -S "(${FUNCNAME[0]}) Proposed MUNKI_REPO_SUBDIR: $app_dev/$app_name"
	else
		local_print --use-echo -Y -S "(${FUNCNAME[0]}) Proposed MUNKI_REPO_SUBDIR: $app_name"
	fi
	local_print --use-echo -Y -S "(${FUNCNAME[0]}) (will actaully use %NAME% in place of app name ($app_name) in plist)"
	get_response "Write proposed changes?"
	if [ $? -eq 0 ]; then
		return_code=0
		/usr/libexec/PlistBuddy "$RECIPE_FILE" -c "set Input:pkginfo:developer $app_dev"
		return_code=$?
		/usr/libexec/PlistBuddy "$RECIPE_FILE" -c "set Input:MUNKI_REPO_SUBDIR $app_dev/%NAME%"
		return_code=$(($return_code+$?))
		if [ $return_code -eq 0 ]; then
			local_print -G -S "(${FUNCNAME[0]}) Successfuly wrote changes to $1"
		else
			local_print -R -S "(${FUNCNAME[0]}) Failed to write changes to $1"
		fi
	else
		local_print -Y -S "(${FUNCNAME[0]}) Skipping write to $1"
	fi
	return 0
}
add_catalog()
{
	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args: $*"
	[ $# -lt 2 ] && fail_notice_exit "(${FUNCNAME[0]}) Missing required argument."
	local RECIPE_FILE=$OVERRIDE_DIR/$1
	local CATALOG="$2"
	local CURRENT_CATALOGS=()
	local c
	while :
	do
		c=$(/usr/libexec/PlistBuddy "$RECIPE_FILE" -c "print Input:pkginfo:catalogs:${#CURRENT_CATALOGS[@]}" 2> /dev/null)
		[ $? -ne 0 ] && break
		CURRENT_CATALOGS=( "${CURRENT_CATALOGS[@]}" "$c" )
	done
	debug_print -B -S "Current Catalogs (${#CURRENT_CATALOGS[@]}): (${CURRENT_CATALOGS[*]})"
	for c in "${CURRENT_CATALOGS[@]}"
	do
		if [[ "$c" == "$CATALOG" ]]; then
			debug_print -B -S "(${FUNCNAME[0]}) Skipping add catalog $CATALOG, because it already exists in (${CURRENT_CATALOGS[*]})"
			return 1
		fi
	done
	CURRENT_CATALOGS=( "${CURRENT_CATALOGS[@]}" "$CATALOG" )
	debug_print -B -S "(${FUNCNAME[0]}) Final catalog (${#CURRENT_CATALOGS[@]}) list to write: (${CURRENT_CATALOGS[*]})"
	write_catalogs "$RECIPE_FILE" "${CURRENT_CATALOGS[@]}"
	return $?
}
remove_catalog()
{
	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args: $*"
	[ $# -lt 2 ] && fail_notice_exit "(${FUNCNAME[0]}) Missing required arguments."
	local RECIPE_FILE=$OVERRIDE_DIR/$1
	local CATALOG="$2"
	local CURRENT_CATALOGS=()
	local c
	while :
	do
		c=$(/usr/libexec/PlistBuddy "$RECIPE_FILE" -c "print Input:pkginfo:catalogs:${#CURRENT_CATALOGS[@]}" 2> /dev/null)
		[ $? -ne 0 ] && break
		CURRENT_CATALOGS=( "${CURRENT_CATALOGS[@]}" "$c" )
	done
	local_print -G -S "Current Catalogs (${#CURRENT_CATALOGS[@]}): (${CURRENT_CATALOGS[*]})"
	[[ "$CATALOG" == "ALL" ]] && CURRENT_CATALOGS=()
	local idx=0
	for c in "${CURRENT_CATALOGS[@]}"
	do
		if [[ "$c" == "$CATALOG" ]]; then
			debug_print -B -S "(${FUNCNAME[0]}) found catalog $CATALOG remove @ index $idx in (${CURRENT_CATALOGS[*]})"
			CURRENT_CATALOGS=( "${CURRENT_CATALOGS[@]:0:$idx}" "${CURRENT_CATALOGS[@]:$(($idx+1))}")
			break
		fi
		((idx++))
	done
	debug_print -B -S "(${FUNCNAME[0]}) Final catalog (${#CURRENT_CATALOGS[@]}) list to write: (${CURRENT_CATALOGS[*]})"
	write_catalogs "$RECIPE_FILE" "${CURRENT_CATALOGS[@]}"
	return $?
}
write_catalogs()
{
	debug_print -e -B -S "(${FUNCNAME[0]}) Started ${FUNCNAME[0]} function with args: $*"
	[ $# -lt 1 ] && fail_notice_exit "(${FUNCNAME[0]}) Missing required argument."
	local RECIPE_FILE=$1
	shift
	local CATALOGS_TO_WRITE="$*"
	local return_code=0
	/usr/libexec/PlistBuddy "$RECIPE_FILE" -c "delete Input:pkginfo:catalogs"
	return_code=$?
	/usr/libexec/PlistBuddy "$RECIPE_FILE" -c "add Input:pkginfo:catalogs array"
	return_code=$(($return_code+$?))
	if [ $return_code -ne 0 ];then
		local_print -R -S "(${FUNCNAME[0]}) Failed to modify catalog array in plist."
		return 1
	fi
	local count=0
	for c in "${CATALOGS_TO_WRITE[@]}"
	do
		local inner_return_code=0
		/usr/libexec/PlistBuddy "$RECIPE_FILE" -c "add Input:pkginfo:catalogs:$count string"
		inner_return_code=$?
		/usr/libexec/PlistBuddy "$RECIPE_FILE" -c "set Input:pkginfo:catalogs:$count $c"
		inner_return_code=$((($inner_return_code+$?)))
		if [ $inner_return_code -eq 0 ]; then
			debug_print -G -S "(${FUNCNAME[0]}) Successfully wrote catalog $c ($(($count+1)) of ${#CURRENT_CATALOGS[@]})"
		else
			return_code=$(($inner_return_code+$return_code))
			debug_print -R -S "(${FUNCNAME[0]}) Failed to write catalog $c ($(($count+1)) of ${#CURRENT_CATALOGS[@]})"
		fi
		((count++))
	done
	return $return_code
}
#### ####

#### Customizable Script Entry ####
if [ $# -lt 1 ] && [ $ARGS_REQUIRED -eq 1 ]; then
	local_print -e -R -S "($0) Missing arguments."
	usage
else
	parse_args "$@"
	main
fi
#### ####

exit 0
